name: Publish Package

on:
  release:
    types: [created]

jobs:
  build:
    permissions:
      packages: write
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./alpine-linux.dockerfile
          push: true
          tags: ghcr.io/atomic-works/alpine-linux:latest
