name: Validate Target Branch

on:
  pull_request:
    types:
    - synchronize
    - opened
    - reopened
    - edited

jobs:
  validate-target-branch:
    uses: atomic-works/github-actions-reusable-workflows/.github/workflows/validate-target-branch.yml@development
    with:
      ubuntu-version: ${{ vars.UBUNTU_VERSION }}
      PR-branch-name: ${{ github.head_ref }}
      base-branch-name: ${{ github.base_ref }}
